In [1]:
!pip install pmdarima
# !pip install statsmodels==0.13.2

Collecting pmdarima
  Downloading pmdarima-1.8.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 4.1 MB/s
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (1.0.2)
Collecting statsmodels!=0.12.0,>=0.11
  Downloading statsmodels-0.13.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 52.0 MB/s
Requirement already satisfied: Cython!=0.29.18,>=0.29 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (0.29.28)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (1.3.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (1.4.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (1.24.3)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (57.4.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (1.1.0)
Requirement already satisfied: numpy>=1.19.3 in /usr/local/lib/python3.7/dist-packages (from pmdarima) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19->pmdarima) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19->pmdarima) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19->pmdarima) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.22->pmdarima) (3.1.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.7/dist-packages (from statsmodels!=0.12.0,>=0.11->pmdarima) (21.3)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.7/dist-packages (from statsmodels!=0.12.0,>=0.11->pmdarima) (0.5.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=21.3->statsmodels!=0.12.0,>=0.11->pmdarima) (3.0.7)
Installing collected packages: statsmodels, pmdarima
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.10.2
    Uninstalling statsmodels-0.10.2:
      Successfully uninstalled statsmodels-0.10.2
Successfully installed pmdarima-1.8.5 statsmodels-0.13.2

In [2]:
import statsmodels
statsmodels.__version__

'0.13.2'

In [3]:
#importando bibliotecas essenciais
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
from pmdarima.arima import auto_arima

> Importando os dados

### Norte

In [4]:
df_norte = pd.read_csv('https://raw.githubusercontent.com/luk3mn/TCC-predicao-de-series-temporais/master/dataset/pld_norte.csv')
# Removendo todos as virgulas do dataset
df_norte.replace(',','.', regex=True, inplace=True)

# Convertendo a coluna "Data" em datetime
df_norte['inicio_semana'] = pd.to_datetime(df_norte['inicio_semana'])

# Tranformando a coluna "Data" em index
df_norte.set_index('inicio_semana', inplace=True)

# Convertendo todos os objetos para valores numericos
c = df_norte.select_dtypes(object).columns
df_norte[c] = df_norte[c].apply(pd.to_numeric,errors='coerce')
df_norte.head()

,preco_pesado,preco_medio,preco_leve,geracao_hidraulica,geracao_termica,carga_energia,reservatorio_EARM,reservatorio_ENA
inicio_semana,,,,,,,,
2001-08-04,684.0,684.0,684.0,2952.29,0.0,2204.00,62.42,89.57
2001-08-11,684.0,684.0,684.0,2956.57,0.0,2141.57,59.75,88.57
2001-08-18,684.0,684.0,684.0,2909.71,0.0,2110.43,56.75,83.86
2001-08-25,684.0,684.0,684.0,2631.00,0.0,2095.43,53.63,79.29
2001-09-01,684.0,684.0,684.0,2558.86,0.0,2069.14,50.64,76.00

### Nordeste

In [ ]:
df_nordeste = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Previsões de séries temporais/teste_com_o_tcc/dataset/pld_nordeste.xlsx')
df_nordeste['inicio_semana'] = pd.to_datetime(df_nordeste['inicio_semana'], dayfirst=True)
df_nordeste.sort_values('inicio_semana', inplace=True)
df_nordeste.set_index('inicio_semana', inplace=True)
df_nordeste.head()

               preco_pesado  preco_medio  ...  reservatorio_EARM  reservatorio_ENA
inicio_semana                             ...
2001-08-04            684.0        684.0  ...              20.09             60.14
2001-08-11            684.0        684.0  ...              19.22             59.86
2001-08-18            684.0        684.0  ...              23.78             62.71
2001-08-25            684.0        684.0  ...              17.29             58.43
2001-09-01            684.0        684.0  ...              16.26             59.14

[5 rows x 8 columns]

### Sul

In [ ]:
df_sul = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Previsões de séries temporais/teste_com_o_tcc/dataset/pld_sul.xlsx')
df_sul['inicio_semana'] = pd.to_datetime(df_sul['inicio_semana'], dayfirst=True)
df_sul.sort_values('inicio_semana', inplace=True)
df_sul.set_index('inicio_semana', inplace=True)
df_sul.head()

               preco_pesado  preco_medio  ...  reservatorio_EARM  reservatorio_ENA
inicio_semana                             ...
2001-08-04            684.0        684.0  ...              20.09             60.14
2001-08-11            684.0        684.0  ...              19.22             59.86
2001-08-18            684.0        684.0  ...              23.78             62.71
2001-08-25            684.0        684.0  ...              17.29             58.43
2001-09-01            684.0        684.0  ...              16.26             59.14

[5 rows x 8 columns]

### Sudeste

In [ ]:
df_sudeste = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Previsões de séries temporais/teste_com_o_tcc/dataset/pld_sudeste.xlsx')
df_sudeste['inicio_semana'] = pd.to_datetime(df_sudeste['inicio_semana'], dayfirst=True)
df_sudeste.sort_values('inicio_semana', inplace=True)
df_sudeste.set_index('inicio_semana', inplace=True)
df_sudeste.head()

               preco_pesado  preco_medio  ...  reservatorio_EARM  reservatorio_ENA
inicio_semana                             ...
2001-08-04            684.0        684.0  ...              20.09             60.14
2001-08-11            684.0        684.0  ...              19.22             59.86
2001-08-18            684.0        684.0  ...              23.78             62.71
2001-08-25            684.0        684.0  ...              17.29             58.43
2001-09-01            684.0        684.0  ...              16.26             59.14

[5 rows x 8 columns]

## Encontrando os parâmetros no dataset de Norte

In [5]:
# stepwise=auto_arima(df_norte.preco_medio,
#                     start_p=1, start_q=1, d=0,
#                     max_p=9, max_q=9, max_d=2,
#                     m=12, 
#                     seasonal=False,
#                     trace=True,
#                     error_action='ignore',suppress_warnings=True,
#                     stepwise=True)

# import pyramid as pm
# stepwise_fit = auto_arima(df_norte['preco_medio'], start_p=1, start_q=1,
#                              max_p=3, max_q=3, m=12, seasonal=False,
#                              d=1,trace=True,
#                              error_action='ignore',  
#                              suppress_warnings=True, 
#                              stepwise=True) 

auto_arima(df_norte.preco_medio, error_action='ignore', trace=1,  seasonal=False)

Performing stepwise search to minimize aic
 ARIMA(2,0,2)(0,0,0)[0]             : AIC=inf, Time=2.16 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=5594.707, Time=0.03 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=inf, Time=0.10 sec
 ARIMA(0,0,1)(0,0,0)[0]             : AIC=5109.385, Time=0.35 sec
 ARIMA(1,0,1)(0,0,0)[0]             : AIC=4371.447, Time=0.33 sec
 ARIMA(2,0,1)(0,0,0)[0]             : AIC=4372.080, Time=0.74 sec
 ARIMA(1,0,2)(0,0,0)[0]             : AIC=4372.546, Time=0.60 sec
 ARIMA(0,0,2)(0,0,0)[0]             : AIC=4836.557, Time=0.55 sec
 ARIMA(2,0,0)(0,0,0)[0]             : AIC=4372.689, Time=0.17 sec
 ARIMA(1,0,1)(0,0,0)[0] intercept   : AIC=4371.000, Time=0.63 sec
 ARIMA(0,0,1)(0,0,0)[0] intercept   : AIC=5005.487, Time=0.48 sec
 ARIMA(1,0,0)(0,0,0)[0] intercept   : AIC=4380.359, Time=0.14 sec
 ARIMA(2,0,1)(0,0,0)[0] intercept   : AIC=4372.495, Time=0.96 sec
 ARIMA(1,0,2)(0,0,0)[0] intercept   : AIC=4372.392, Time=1.22 sec
 ARIMA(0,0,0)(0,0,0)[0] intercept   : AIC=5469.450, Time=0.04 sec
 ARIMA(0,0,2)(0,0,0)[0] intercept   : AIC=4757.178, Time=1.36 sec
 ARIMA(2,0,0)(0,0,0)[0] intercept   : AIC=4372.176, Time=0.50 sec
 ARIMA(2,0,2)(0,0,0)[0] intercept   : AIC=inf, Time=1.72 sec

Best model:  ARIMA(1,0,1)(0,0,0)[0] intercept
Total fit time: 12.166 seconds

ARIMA(order=(1, 0, 1), scoring_args={}, suppress_warnings=True)

## Encontrando os parâmetros no dataset Nordeste

In [ ]:
stepwise=auto_arima(df_nordeste.preco_medio,
                    start_p=1, start_q=1, d=0,
                    max_p=6, max_q=6, max_d=2,
                    m=12, 
                    seasonal=False,
                    trace=True,
                    error_action='ignore',suppress_warnings=True,
                    stepwise=True)

/usr/local/lib/python3.7/dist-packages/pmdarima/arima/_validation.py:62: UserWarning: m (12) set for non-seasonal fit. Setting to 0
  warnings.warn("m (%i) set for non-seasonal fit. Setting to 0" % m)

Performing stepwise search to minimize aic
 ARIMA(1,0,1)(0,0,0)[0]             : AIC=4461.820, Time=0.09 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=5778.932, Time=0.01 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=4462.245, Time=0.04 sec
 ARIMA(0,0,1)(0,0,0)[0]             : AIC=5272.326, Time=0.11 sec
 ARIMA(2,0,1)(0,0,0)[0]             : AIC=4452.964, Time=0.16 sec
 ARIMA(2,0,0)(0,0,0)[0]             : AIC=4461.996, Time=0.08 sec
 ARIMA(3,0,1)(0,0,0)[0]             : AIC=4454.904, Time=0.32 sec
 ARIMA(2,0,2)(0,0,0)[0]             : AIC=4454.911, Time=0.28 sec
 ARIMA(1,0,2)(0,0,0)[0]             : AIC=4462.846, Time=0.16 sec
 ARIMA(3,0,0)(0,0,0)[0]             : AIC=4463.321, Time=0.12 sec
 ARIMA(3,0,2)(0,0,0)[0]             : AIC=4455.749, Time=0.54 sec
 ARIMA(2,0,1)(0,0,0)[0] intercept   : AIC=4452.968, Time=0.31 sec

Best model:  ARIMA(2,0,1)(0,0,0)[0]
Total fit time: 2.247 seconds

## Encontrando os parâmetros no dataset Sul

In [ ]:
stepwise=auto_arima(df_sul.preco_medio,
                    start_p=1, start_q=1, d=0,
                    max_p=6, max_q=6, max_d=2,
                    m=12, 
                    seasonal=False,
                    trace=True,
                    error_action='ignore',suppress_warnings=True,
                    stepwise=True)

/usr/local/lib/python3.7/dist-packages/pmdarima/arima/_validation.py:62: UserWarning: m (12) set for non-seasonal fit. Setting to 0
  warnings.warn("m (%i) set for non-seasonal fit. Setting to 0" % m)

Performing stepwise search to minimize aic
 ARIMA(1,0,1)(0,0,0)[0]             : AIC=4461.820, Time=0.11 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=5778.932, Time=0.01 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=4462.245, Time=0.04 sec
 ARIMA(0,0,1)(0,0,0)[0]             : AIC=5272.326, Time=0.11 sec
 ARIMA(2,0,1)(0,0,0)[0]             : AIC=4452.964, Time=0.16 sec
 ARIMA(2,0,0)(0,0,0)[0]             : AIC=4461.996, Time=0.08 sec
 ARIMA(3,0,1)(0,0,0)[0]             : AIC=4454.904, Time=0.30 sec
 ARIMA(2,0,2)(0,0,0)[0]             : AIC=4454.911, Time=0.29 sec
 ARIMA(1,0,2)(0,0,0)[0]             : AIC=4462.846, Time=0.16 sec
 ARIMA(3,0,0)(0,0,0)[0]             : AIC=4463.321, Time=0.12 sec
 ARIMA(3,0,2)(0,0,0)[0]             : AIC=4455.749, Time=0.52 sec
 ARIMA(2,0,1)(0,0,0)[0] intercept   : AIC=4452.968, Time=0.32 sec

Best model:  ARIMA(2,0,1)(0,0,0)[0]
Total fit time: 2.229 seconds

## Encontrando os parâmetros no dataset Sul