In [ ]:
#importando bibliotecas essenciais
import pandas as pd
import numpy as np
from statsmodels.tsa.arima_model import ARIMA
import warnings
import itertools
warnings.filterwarnings("ignore") # specify to ignore warning messages

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

> Importando os dados

### Norte

In [ ]:
df_norte = pd.read_csv('https://raw.githubusercontent.com/luk3mn/TCC-predicao-de-series-temporais/master/dataset/pld_norte.csv')
# Removendo todos as virgulas do dataset
df_norte.replace(',','.', regex=True, inplace=True)

# Convertendo a coluna "Data" em datetime
df_norte['inicio_semana'] = pd.to_datetime(df_norte['inicio_semana'])

# Tranformando a coluna "Data" em index
df_norte.set_index('inicio_semana', inplace=True)

# Convertendo todos os objetos para valores numericos
c = df_norte.select_dtypes(object).columns
df_norte[c] = df_norte[c].apply(pd.to_numeric,errors='coerce')
df_norte.head()

,preco_pesado,preco_medio,preco_leve,geracao_hidraulica,geracao_termica,carga_energia,reservatorio_EARM,reservatorio_ENA
inicio_semana,,,,,,,,
2001-08-04,684.0,684.0,684.0,2952.29,0.0,2204.00,62.42,89.57
2001-08-11,684.0,684.0,684.0,2956.57,0.0,2141.57,59.75,88.57
2001-08-18,684.0,684.0,684.0,2909.71,0.0,2110.43,56.75,83.86
2001-08-25,684.0,684.0,684.0,2631.00,0.0,2095.43,53.63,79.29
2001-09-01,684.0,684.0,684.0,2558.86,0.0,2069.14,50.64,76.00

### Nordeste

In [ ]:
df_nordeste = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Previsões de séries temporais/teste_com_o_tcc/dataset/pld_nordeste.xlsx')
df_nordeste['inicio_semana'] = pd.to_datetime(df_nordeste['inicio_semana'], dayfirst=True)
df_nordeste.sort_values('inicio_semana', inplace=True)
df_nordeste.set_index('inicio_semana', inplace=True)
df_nordeste.head()

               preco_pesado  preco_medio  ...  reservatorio_EARM  reservatorio_ENA
inicio_semana                             ...
2001-08-04            684.0        684.0  ...              20.09             60.14
2001-08-11            684.0        684.0  ...              19.22             59.86
2001-08-18            684.0        684.0  ...              23.78             62.71
2001-08-25            684.0        684.0  ...              17.29             58.43
2001-09-01            684.0        684.0  ...              16.26             59.14

[5 rows x 8 columns]

### Sul

In [ ]:
df_sul = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Previsões de séries temporais/teste_com_o_tcc/dataset/pld_sul.xlsx')
df_sul['inicio_semana'] = pd.to_datetime(df_sul['inicio_semana'], dayfirst=True)
df_sul.sort_values('inicio_semana', inplace=True)
df_sul.set_index('inicio_semana', inplace=True)
df_sul.head()

               preco_pesado  preco_medio  ...  reservatorio_EARM  reservatorio_ENA
inicio_semana                             ...
2001-08-04            684.0        684.0  ...              20.09             60.14
2001-08-11            684.0        684.0  ...              19.22             59.86
2001-08-18            684.0        684.0  ...              23.78             62.71
2001-08-25            684.0        684.0  ...              17.29             58.43
2001-09-01            684.0        684.0  ...              16.26             59.14

[5 rows x 8 columns]

### Sudeste

In [ ]:
df_sudeste = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Previsões de séries temporais/teste_com_o_tcc/dataset/pld_sudeste.xlsx')
df_sudeste['inicio_semana'] = pd.to_datetime(df_sudeste['inicio_semana'], dayfirst=True)
df_sudeste.sort_values('inicio_semana', inplace=True)
df_sudeste.set_index('inicio_semana', inplace=True)
df_sudeste.head()

               preco_pesado  preco_medio  ...  reservatorio_EARM  reservatorio_ENA
inicio_semana                             ...
2001-08-04            684.0        684.0  ...              20.09             60.14
2001-08-11            684.0        684.0  ...              19.22             59.86
2001-08-18            684.0        684.0  ...              23.78             62.71
2001-08-25            684.0        684.0  ...              17.29             58.43
2001-09-01            684.0        684.0  ...              16.26             59.14

[5 rows x 8 columns]

## Encontrando os parâmetros para a base de dados do PLD

In [ ]:
def find_params(data, p_min, p_max, q_min, q_max, d_max):
    # Define the p, d and q parameters to take any value between 0 and 2
    p = range(p_min, (p_max+1))
    d = range(0, (d_max+1))
    q = range(q_min, (q_max+1))

    # Generate all different combinations of p, q and q triplets
    pdq = list(itertools.product(p, d, q))

    aic=[]
    for param in pdq:
        try:
            mod = ARIMA(data, order=param)
            results = mod.fit(disp=0)
            aic.append(results.aic)
            # pega o melhor modelo
            if (np.min(aic) == results.aic):
                min_aic=results.aic
                best_model=param
            print('ARIMA{} - AIC:{}'.format(param, results.aic))
        except:
            continue
    print("\n========================================")
    print("             MELHOR MODELO               ")
    print("----------------------------------------")
    print('ARIMA{} - AIC:{}'.format(best_model, min_aic))
    print("========================================")

## Encontrando os parâmetros no dataset PLD Norte

In [ ]:
find_params(df_norte['preco_medio'],0,9,0,9,3)

ARIMA(0, 0, 0) - AIC:5469.449825236253
ARIMA(0, 0, 1) - AIC:5005.486868110417
ARIMA(0, 1, 0) - AIC:4366.051478335235
ARIMA(0, 1, 1) - AIC:4358.976659621956
ARIMA(0, 1, 2) - AIC:4359.194093223194
ARIMA(0, 1, 3) - AIC:4359.795591114114
ARIMA(0, 1, 4) - AIC:4356.248627070969
ARIMA(0, 1, 5) - AIC:4354.456026148959
ARIMA(0, 1, 6) - AIC:4355.318611412953
ARIMA(0, 1, 7) - AIC:4350.767383390851
ARIMA(0, 1, 8) - AIC:4336.0345342392875
ARIMA(0, 1, 9) - AIC:4335.98940598577
ARIMA(0, 2, 0) - AIC:4600.365564023802
ARIMA(0, 2, 1) - AIC:4363.3352028493
ARIMA(0, 2, 2) - AIC:4356.449390192005
ARIMA(1, 0, 0) - AIC:4380.359052095902
ARIMA(1, 0, 1) - AIC:4370.99999093259
ARIMA(1, 0, 2) - AIC:4372.39174452298
ARIMA(1, 0, 3) - AIC:4374.027712792201
ARIMA(1, 0, 4) - AIC:4371.869887289171
ARIMA(1, 0, 5) - AIC:4370.623379927911
ARIMA(1, 0, 6) - AIC:4371.207351749637
ARIMA(1, 0, 7) - AIC:4366.280360504887
ARIMA(1, 0, 8) - AIC:4351.954598910074
ARIMA(1, 0, 9) - AIC:4351.871510842799
ARIMA(1, 1, 0) - AIC:4360.285199787946
ARIMA(1, 1, 1) - AIC:4359.805639204562
ARIMA(1, 1, 2) - AIC:4356.159780495504
ARIMA(1, 1, 3) - AIC:4357.830664825157
ARIMA(1, 1, 4) - AIC:4356.464614560071
ARIMA(1, 1, 9) - AIC:4337.253389414303
ARIMA(1, 2, 0) - AIC:4532.323315913782
ARIMA(1, 2, 1) - AIC:4357.75880476912
ARIMA(1, 2, 2) - AIC:4355.495963547533
ARIMA(1, 2, 3) - AIC:4353.549555497363
ARIMA(1, 2, 7) - AIC:4348.42524570141
ARIMA(2, 0, 0) - AIC:4372.176394997383
ARIMA(2, 0, 1) - AIC:4372.494779236207
ARIMA(2, 1, 0) - AIC:4358.79381884931
ARIMA(2, 1, 1) - AIC:4355.260807165728
ARIMA(2, 1, 2) - AIC:4356.920645095427
ARIMA(2, 1, 3) - AIC:4353.737192600729
ARIMA(2, 1, 4) - AIC:4341.173822021996
ARIMA(2, 1, 5) - AIC:4341.262680529066
ARIMA(2, 2, 0) - AIC:4490.958561588935
ARIMA(2, 2, 1) - AIC:4356.149016867546
ARIMA(2, 2, 2) - AIC:4354.2425985769805
ARIMA(2, 2, 3) - AIC:4344.499767174811
ARIMA(2, 2, 7) - AIC:4333.2143783590745
ARIMA(2, 2, 8) - AIC:4335.173823171962
ARIMA(2, 2, 9) - AIC:4338.422170534978
ARIMA(3, 0, 0) - AIC:4372.183035110596
ARIMA(3, 0, 1) - AIC:4371.185069813233
ARIMA(3, 0, 2) - AIC:4363.163674852924
ARIMA(3, 1, 0) - AIC:4359.564168049747
ARIMA(3, 1, 1) - AIC:4357.102167768363
ARIMA(3, 1, 2) - AIC:4354.317262689053
ARIMA(3, 1, 3) - AIC:4351.166543123313
ARIMA(3, 1, 4) - AIC:4341.227096879775
ARIMA(3, 2, 0) - AIC:4477.509017005533
ARIMA(3, 2, 1) - AIC:4356.819224740958
ARIMA(3, 2, 2) - AIC:4353.9740017142285
ARIMA(3, 2, 7) - AIC:4335.424379222235
ARIMA(3, 2, 8) - AIC:4337.371421733367
ARIMA(3, 2, 9) - AIC:4337.473152301213
ARIMA(4, 0, 0) - AIC:4373.657518522325
ARIMA(4, 0, 1) - AIC:4373.060438879389
ARIMA(4, 0, 2) - AIC:4374.492800614376
ARIMA(4, 0, 3) - AIC:4357.539582988939
ARIMA(4, 1, 0) - AIC:4354.906693192457
ARIMA(4, 1, 1) - AIC:4356.381238230179
ARIMA(4, 1, 2) - AIC:4340.631237168137
ARIMA(4, 1, 3) - AIC:4342.064344676982
ARIMA(4, 2, 0) - AIC:4456.891126787098
ARIMA(4, 2, 1) - AIC:4351.830482329987
ARIMA(4, 2, 2) - AIC:4353.603898042605
ARIMA(4, 2, 3) - AIC:4355.146686204999
ARIMA(4, 2, 7) - AIC:4326.9239383030435
ARIMA(4, 2, 8) - AIC:4328.689681304886
ARIMA(4, 2, 9) - AIC:4330.449541001239
ARIMA(5, 0, 0) - AIC:4370.4506071381165
ARIMA(5, 0, 1) - AIC:4369.763376314355
ARIMA(5, 0, 2) - AIC:4372.494449878759
ARIMA(5, 0, 3) - AIC:4369.660759593109
ARIMA(5, 0, 4) - AIC:6066.024371443272
ARIMA(5, 1, 0) - AIC:4355.875030089631
ARIMA(5, 1, 1) - AIC:4357.35950120575
ARIMA(5, 1, 2) - AIC:4342.175051300916
ARIMA(5, 2, 0) - AIC:4425.8784427551855
ARIMA(5, 2, 1) - AIC:4352.618102432444
ARIMA(5, 2, 2) - AIC:4350.415924262177
ARIMA(5, 2, 3) - AIC:4344.721780742505
ARIMA(5, 2, 4) - AIC:4336.233845490764
ARIMA(5, 2, 7) - AIC:4323.144983313748
ARIMA(5, 2, 8) - AIC:4330.13574986535
ARIMA(5, 2, 9) - AIC:4331.803913291349
ARIMA(6, 0, 0) - AIC:4371.832693923212
ARIMA(6, 0, 1) - AIC:4373.268052818401
ARIMA(6, 0, 3) - AIC:4362.770185253483
ARIMA(6, 0, 5) - AIC:4376.454506420115
ARIMA(6, 1, 0) - AIC:4356.277954563542
ARIMA(6, 1, 1) - AIC:4358.268425276646
ARIMA(6, 1, 2) - AIC:4344.166936857302
ARIMA(6, 1, 3) - AIC:4338.911969310216
ARIMA(6, 2, 0) - AIC:4411.0998856321585
ARIMA(6, 2, 1) - AIC:4353.228645995748
ARIMA(6, 2, 2) - AIC:4348.884542578193
ARIMA(6, 2, 3) - AIC:4335.260242406661
ARIMA(6, 2, 4) - AIC:4335.83095673358
ARIMA(6, 2, 5) - AIC:4331.768147329103
ARIMA(6, 2, 6) - AIC:4323.5301653083
ARIMA(6, 2, 7) - AIC:4319.131422211544
ARIMA(6, 2, 8) - AIC:4320.671986719204
ARIMA(6, 2, 9) - AIC:4322.509458045629
ARIMA(7, 0, 0) - AIC:4371.553293307127
ARIMA(7, 0, 1) - AIC:4368.997693531643
ARIMA(7, 0, 2) - AIC:4354.994636411426
ARIMA(7, 0, 3) - AIC:4354.3715700294215
ARIMA(7, 0, 4) - AIC:4355.179430647991
ARIMA(7, 0, 5) - AIC:4338.606000412858
ARIMA(7, 0, 6) - AIC:4339.566655532343
ARIMA(7, 1, 0) - AIC:4358.212590732669
ARIMA(7, 1, 1) - AIC:4351.475447461204
ARIMA(7, 1, 2) - AIC:4339.782524358505
ARIMA(7, 1, 3) - AIC:4342.091159863956
ARIMA(7, 2, 0) - AIC:4413.040425519908
ARIMA(7, 2, 1) - AIC:4355.170652866012
ARIMA(7, 2, 2) - AIC:4348.457426546865
ARIMA(7, 2, 3) - AIC:4336.79555739342
ARIMA(7, 2, 4) - AIC:4338.692956088039
ARIMA(7, 2, 7) - AIC:4328.148529455125
ARIMA(7, 2, 8) - AIC:4317.662321707275
ARIMA(7, 2, 9) - AIC:4340.241359907446
ARIMA(8, 0, 0) - AIC:4373.382494118854
ARIMA(8, 0, 1) - AIC:4366.592502739362
ARIMA(8, 0, 2) - AIC:4355.925726153575
ARIMA(8, 0, 3) - AIC:4355.855324622794
ARIMA(8, 0, 4) - AIC:4345.863120911265
ARIMA(8, 0, 5) - AIC:4359.007119894537
ARIMA(8, 0, 6) - AIC:4354.963146615823
ARIMA(8, 1, 0) - AIC:4349.690610855702
ARIMA(8, 1, 1) - AIC:4351.688863600263
ARIMA(8, 1, 2) - AIC:4353.591581002432
ARIMA(8, 1, 3) - AIC:4343.335116853347
ARIMA(8, 1, 5) - AIC:4334.944811367716
ARIMA(8, 1, 6) - AIC:4329.14525175725
ARIMA(8, 1, 7) - AIC:4322.282695778947
ARIMA(8, 1, 8) - AIC:4326.082972701508
ARIMA(8, 2, 0) - AIC:4403.2939671501235
ARIMA(8, 2, 1) - AIC:4346.409687917816
ARIMA(8, 2, 2) - AIC:4348.402367375575
ARIMA(8, 2, 3) - AIC:4352.528351191838
ARIMA(8, 2, 7) - AIC:4338.297028893886
ARIMA(8, 2, 8) - AIC:4333.876326165777
ARIMA(8, 2, 9) - AIC:4323.071014237463
ARIMA(9, 0, 0) - AIC:4365.822802622111
ARIMA(9, 0, 1) - AIC:4367.818276571037
ARIMA(9, 0, 2) - AIC:4369.648888432563
ARIMA(9, 0, 3) - AIC:4355.837168558324
ARIMA(9, 0, 4) - AIC:4357.835606775008
ARIMA(9, 0, 5) - AIC:4359.686464320379
ARIMA(9, 0, 6) - AIC:4342.957342769683
ARIMA(9, 0, 7) - AIC:4342.034900506702
ARIMA(9, 0, 8) - AIC:5854.626951853732
ARIMA(9, 0, 9) - AIC:4357.720864088851
ARIMA(9, 1, 0) - AIC:4351.688456384431
ARIMA(9, 1, 1) - AIC:4353.375199968741
ARIMA(9, 1, 2) - AIC:4355.374691608726
ARIMA(9, 1, 3) - AIC:4357.265584952275
ARIMA(9, 1, 4) - AIC:4344.200632686866
ARIMA(9, 1, 5) - AIC:4350.076079817982
ARIMA(9, 1, 6) - AIC:4350.930860081047
ARIMA(9, 1, 7) - AIC:4339.265270808115
ARIMA(9, 1, 8) - AIC:4332.559827624532
ARIMA(9, 1, 9) - AIC:4334.095840092604
ARIMA(9, 2, 0) - AIC:4394.465951230928
ARIMA(9, 2, 1) - AIC:4348.400896589858
ARIMA(9, 2, 2) - AIC:4345.838842454864
ARIMA(9, 2, 3) - AIC:4339.392600998311
ARIMA(9, 2, 4) - AIC:4339.733749120013
ARIMA(9, 2, 5) - AIC:4334.21431424143
ARIMA(9, 2, 6) - AIC:4339.897193742411
ARIMA(9, 2, 7) - AIC:4327.917788109213
ARIMA(9, 2, 8) - AIC:4331.383681341292
ARIMA(9, 2, 9) - AIC:4331.979466122631

========================================
             MELHOR MODELO
----------------------------------------
ARIMA(7, 2, 8) - AIC:4317.662321707275
========================================